service: ikman-crawler

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "ssm:GetParameter"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "arn:aws:secretsmanager:us-east-1:310340543340:secret:gsheet_client_secret-eq2CuG"
    - Effect: "Allow" 
      Action:
        - "ses:SendEmail"
      Resource: "*"      

functions:
  house_crawler:
    handler: house_crawler.handler
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:310340543340:layer:ikman-crawler-dependencies:1
    events:
      - schedule: cron(30 23 * * ? *)

  description_processor:
    handler: description_processor.handler
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:310340543340:layer:ikman-crawler-dependencies:1
    events:
      - schedule: cron(45 23 * * ? *)
      - schedule: cron(0 0 * * ? *)

  duplicate_processor:
    handler: duplicate_processor.handle
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:310340543340:layer:ikman-crawler-dependencies:1
    events:
      - schedule: cron(15 0 * * ? *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux