service: ikman-crawler

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "ssm:GetParameter"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "${env:SECRET_ARN}"
    - Effect: "Allow" 
      Action:
        - "ses:SendEmail"
      Resource: "*"      
  environment:
    SECRET_ARN: ${env:SECRET_ARN}

functions:
  house_crawler:
    handler: src/house_crawler.handler
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:${env:AWS_ACCOUNT}:layer:ikman-crawler-dependencies:1

  description_processor:
    handler: src/description_processor.handler
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:${env:AWS_ACCOUNT}:layer:ikman-crawler-dependencies:1

  duplicate_processor:
    handler: src/duplicate_processor.handle
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:${env:AWS_ACCOUNT}:layer:ikman-crawler-dependencies:1
      
  land_crawler:
    handler: src/land_crawler.handler
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:${env:AWS_ACCOUNT}:layer:ikman-crawler-dependencies:1

  house_rent_crawler:
    handler: src/house_rent_crawler.handler
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:${env:AWS_ACCOUNT}:layer:ikman-crawler-dependencies:1

  house_rent_notifier:
    handler: src/house_rent_notifier.handle
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:${env:AWS_ACCOUNT}:layer:ikman-crawler-dependencies:1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  include:
    - src/**
